{% set version = "0.3.11" %}

package:
  name: damageprofiler
  version: {{ version }}

source:
  fn: DamageProfiler-{{ version }}.jar
  url: https://github.com/Integrative-Transcriptomics/DamageProfiler/releases/download/v{{ version }}/DamageProfiler-{{ version }}.jar
  md5: cba8615f970e207873f5ec21eda507ca 

build:
  number: 0

requirements:
  run:
    - openjdk
    - python

test:
  commands:
    - damageprofiler -h  >/dev/null

about:
  home: https://github.com/Integrative-Transcriptomics/dedup 
  license: GPLv3
  summary: " A Java based tool to determine damage patterns on ancient DNA as a replacement for mapDamage "
