
package:
  name: schmutzi
  version: 1.5.4

build:
  number: 0
  script: 
  - git submodule update
  - make

source:
  git_url: https://github.com/grenaud/schmutzi
  git_rev: v1.5.4

requirements:
  build:
    - gcc   # [linux]
    - zlib {{CONDA_ZLIB}}*
    - wget
    - perl {{CONDA_PERL}}* 
    - cmake
    - R

  run:
    - zlib {{CONDA_ZLIB}}*
    - libgcc
    - perl {{CONDA_PERL}}*
    - R 
    - r-fitdistrplus

test:
  commands:
    - contDeam > /dev/null
    - endoCaller > /dev/null
    - mtCont  > /dev/null
    - approxDist.R > /dev/null
    - schmutzi.pl > /dev/null
    - mtCont > /dev/null
    - bam2prof > /dev/null
    - insertSize > /dev/null
    - log2freq > /dev/null
    - logs2pos > /dev/null
    - mitoConsPDF.R > /dev/null
    - mas2freq > /dev/null
    - mas2log > /dev/null
    - posteriorDeam.R  > /dev/null
    - contOut2ContEst.pl > /dev/null


about:
  home: https://github.com/grenaud/schmutzi
  license: unknown
  summary: Maximum a posteriori estimate of contamination for ancient samples.

extra:
  skip-lints:
    - uses_git_url
    - missing_hash
