{% set version = "1.0" %}
{% set sha256 = "9d593872715bf510e66163267ce14e1208ecbdd7017695738610f25b74930f9b" %}

package:
  name: ruby-dna-tools
  version: {{ version }}

source:
  fn: ruby-dna-tools_{{ version }}.tar.gz
  url: https://github.com/Carldeboer/Ruby-DNA-Tools/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - zlib
    - gcc [linux]
    - llvm  [osx]
    - python
    - yaml
    - libxml2
    - openssl 1.0.1g
    - libffi
    - toolchain3
    - make
    - cmake
    - openssl 1.0.*
    - zlib 1.2.11
    - readline 7.0
    - tk 8.6.*
    - yaml
    - gettext  # [osx]
    - gmp 6.1.*
  run:
    - ruby 2.4
    - jemalloc 4.4

test:
    commands:
      - ruby -e 'require "UTILS.rb";'

about:
  home: https://github.com/Carldeboer/Ruby-DNA-Tools
  license: GPL-2.0
  summary: Various libraries containing useful functions for working with DNA sequences, written in ruby. Some tools are not specific to DNA.
