{% set version = "0.3.2" %}
{% set sha256 = "789822f8c06202705dd927396bda13561a14cab6239b07d19721ff98a916f142" %}

package:
  name: krakenhll
  version: {{ version }}

source:
  fn: krakenhll-{{ version }}.tar.gz
  url: https://github.com/fbreitwieser/krakenhll/archive/d17b6a0aea43774cbe7e559c6ef8cb35fffd1844.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  has_prefix_files:
    - libexec/krakenhll
    - libexec/krakenhll-build
    - libexec/krakenhll-filter
    - libexec/krakenhll-mpa-report
    - libexec/krakenhll-report
    - libexec/krakenhll-translate

requirements:
  build:
    - perl
    - gcc 
    - zlib {{CONDA_ZLIB}}*

  run:
    - jellyfish 1.*
    - perl
    - perl-libwww-perl
    - perl-lwp-protocol-https
    - libgcc
    - zlib {{CONDA_ZLIB}}*

test:
  commands:
    - krakenhll --version
    - krakenhll-build --version
    - krakenhll-extract-reads --help 2>&1 | grep Usage
    - krakenhll-filter --version
    - krakenhll-mpa-report --version
    - krakenhll-report --version
    - krakenhll-translate --version

about:
  home: https://github.com/fbreitwieser/krakenhll
  license: GPLv3
  license_file: LICENSE
  summary: KrakenHLL metagenomics classification method with unique k-mer counting for more specific results
