{% set version = "1.2.1" %}


package:
  name: shmlast
  version: {{ version }}

source:
  url: https://github.com/camillescott/shmlast/archive/v{{ version }}.tar.gz
  fn: shmlast-{{version}}.tar.gz
  sha256: 7c9722a532de2478af97f78add357203d33076a3fe086cabd70d241d8127da3e

build:
  number: 0
  skip: True # [py27]
  script: python setup.py install --record record.txt

requirements:
  build:
    # Python dependencies
    - python 
    - numpy
    - pandas
    - numexpr >=2.3.1
    - ficus >=0.5
    - doit >=0.29.0
    - matplotlib
    - scipy >=0.16.0
    - screed >=0.9
    - seaborn >=0.6.0
    - pytest
    - pytest-runner
    - filelock >=2.0.6

    # Other
    - last
    - parallel

  run:
    # Python dependencies
    - python 
    - numpy
    - pandas
    - numexpr >=2.3.1
    - ficus >=0.5
    - doit >=0.29.0
    - matplotlib
    - scipy >=0.16.0
    - screed >=0.9
    - seaborn >=0.6.0
    - pytest
    - filelock >=2.0.6

    # Other
    - last
    - parallel

test:
  imports:
    #

  commands:
    - pytest --pyargs shmlast -k besthits

about:
  home: https://github.com/camillescott/shmlast
  license: BSD-3-Clause
  license_file: LICENSE
  summary: conditional reciprocal best hits with LAST
