{% set version = "1.2" %}


package:
  name: shmlast
  version: {{ version }}

source:
  url: https://github.com/camillescott/shmlast/archive/v{{ version }}.tar.gz
  fn: shmlast-{{version}}.tar.gz
  sha256: 1f182e404e0cfab5fda05d69cd46e76ba04fb43b6931d97c6b4b59df78844354

build:
  number: 0
  skip: True # [py27]
  script: python setup.py install --record record.txt

requirements:
  build:
    # Python dependencies
    - python 
    - numpy
    - pandas
    - numexpr >=2.3.1
    - ficus >=0.4.1
    - doit >=0.29.0
    - matplotlib
    - scipy >=0.16.0
    - screed >=0.9
    - seaborn >=0.6.0
    - pytest
    - pytest-runner
    - filelock >=2.0.6

    # Other
    - last
    - parallel

  run:
    # Python dependencies
    - python 
    - numpy
    - pandas
    - numexpr >=2.3.1
    - ficus >=0.4.1
    - doit >=0.29.0
    - matplotlib
    - scipy >=0.16.0
    - screed >=0.9
    - seaborn >=0.6.0
    - pytest
    - filelock >=2.0.6

    # Other
    - last
    - parallel

test:
  imports:
    #

  commands:
    - shmlast -h > /dev/null

about:
  home: https://github.com/camillescott/shmlast
  license: BSD-3-Clause
  license_file: LICENSE
  summary: conditional reciprocal best hits with LAST
