{% set version = "0.2.3" %}

package:
  name: rust-bio-tools
  version: {{version}}

build:
  number: 0
  # TODO wait for CB3 gcc, then try again.
  skip: true  # [osx]

source:
  fn: rust-bio-tools-{{version}}.tar.gz
  url: https://github.com/rust-bio/rust-bio-tools/archive/{{version}}.tar.gz
  sha256: 372612df76819fe3c389e2c73e7d75cf1df87cb9854407a95a154de015e7c43d

requirements:
  build:
    - rust
    - gcc <4.8.5
    - zlib {{ CONDA_ZLIB }}*
  run:
    - zlib {{ CONDA_ZLIB }}*
    - libgcc

test:
  commands:
    - rbt --help

about:
  home: https://github.com/rust-bio/rust-bio-tools
  license: MIT
  summary: |
    A growing collection of fast and secure command line utililities for dealing with NGS data
    implemented on top of Rust-Bio.
