{% set version = "0.91" %}

package:
  name: vcf2genome
  version: {{ version }}

source:
  fn: VCF2Genome-{{ version }}.jar
  url: https://github.com/apeltzer/vcf2genome/releases/download/v{{ version }}/VCF2Genome-{{ version }}.jar
  md5: 5a0dd98d719e9658898bebf25d8e18ad 

build:
  number: 0

requirements:
  run:
    - openjdk
    - python

test:
  commands:
    - vcf2genome -h  >/dev/null

about:
  home: https://github.com/apeltzer/vcf2genome 
  license: GPLv3
  summary: "A tool to create a draft genome file out of a GATK VCF file and enabling users to filter the VCF in a single step"
