{% set version = "0.4.2" %}

package:
  name: ficus
  version: {{ version }}

source:
  fn: ficus-{{ version }}.tar.gz
  url: https://github.com/camillescott/ficus/archive/v{{ version }}.tar.gz
  sha256: c3a36842c478917eaea954b40c02c3f203c79d79d6625ea0513edc71a4e75a33

build:
  number: 0

requirements:
  build:
    - python
    - matplotlib >=1.4
    - setuptools >=0.6.35
    - pytest
    - pytest-runner

  run:
    - python
    - matplotlib >=1.4
    - libgcc # [not osx]
    - mesalib

test:
  # Python imports
  imports:
    - ficus

about:
  home: https://github.com/camillescott/ficus
  license: BSD-3-Clause
  summary: provides a context manager for matplotlib figures. 
