package:
  name: ficus
  version: "0.4.1"

source:
  fn: ficus-0.4.1.tar.gz
  url: https://github.com/camillescott/ficus/archive/v0.4.1.tar.gz
  sha256: ac2093db666e3ba946bbee1cab729c22bef09b0d877f1e96803bed3e28bf027d

build:
  number: 0

requirements:
  build:
    - python
    - matplotlib >=1.4
    - setuptools >=0.6.35
    - pytest
    - pytest-runner

  run:
    - python
    - matplotlib >=1.4

test:
  # Python imports
  imports:
    - ficus

about:
  home: https://github.com/camillescott/ficus
  license: BSD-3-Clause
  summary: provides a context manager for matplotlib figures. 
